#!/usr/bin/python3
"""Checks for errors unlike previous tasks"""
from urllib import request, error
from sys import argv


if __name__ == "__main__":
    url = argv[1]
    req = request.Request(url)
    try:
        with request.urlopen(req) as response:
            print(response.read().decode('utf-8'))
    except error.HTTPError as e:
        print("Error code: {}".format(e.code))
