#!/usr/bin/python3


def raise_exception_msg(message=""):
    a = "fun"
    print("C is {}".format(a))
